[main]
debug = false
extra_debug = false

[mattermost]
server = "https://localhost:8065"
insecure_tls = false
debugChannel = "Networking:yobot-test"

[mattermost.login]
username = ""
password = ""

[mattermost.botid]
firstname = "Yobot"
lastname = ""
nickname = "yobot"

[http]
address = ":8080"

[team.Networking]
channels = ["Yobot-Test"]

[routes.default]
channels = ["Networking:yobot-test"]
username = ""
password = ""

[routes.grafana]
enabled = true

[routes.general]
enabled = true

[routes.librenms]
enabled = true

# Route sysContact information to a specific channel
[routes.librenms.settings.routes]
"*" = "Global:NOC" # Asterisk matches everything so all alerts will go here
"email@example.com" = "Server-Admins:NOC" # Key is taken literally
"/email@example.com/" = "Server-Admins:NOC" # Key is a regular expression

[routes.git]
enabled = true

[routes.git.settings]
secret = "mysecret"

[routes.git-issues]
enabled = true

[routes.git-issues.settings]
secret = "mysecret"

# With will add /msgbus/custom which will be processed as it went to /msgbus/general
# This allows custom channels or basic auth for a specific application but allows it
# to use the same processing handler as something else.
# [routes.custom]
# alias = "general" # Use the same handler as the general route, must be a builin handler
# username = "john"
# password = "change me"

# Module configurations are case sensative.

# [[modules.meetbot]]
# AllowedChannels = ["#bottest"]

# [[modules.dandelion]]
# URL = "https://dandelion.example.com"
# ApiKey = "123456789"
# Channels = ["Networking:noc"]
