[main]
debug = false
extra_debug = false

[mattermost]
server = "https://localhost:8065"
insecure_tls = false
debugChannel = "Networking:yobot-test"

[mattermost.login]
username = ""
password = ""

[mattermost.botid]
firstname = "Yobot"
lastname = ""
nickname = "yobot"

[team.Networking]
channels = ["Yobot-Test"]
